version: '3.4'

services:
  redis:
    image: redis:latest

  redis-test:
    image: redis:latest

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Microservices/IdentityService/Identity.Api/Dockerfile

  categories.api:
    image: ${DOCKER_REGISTRY-}categoriesapi
    build:
      context: .
      dockerfile: Microservices/CategoriesService/Categories.Api/Dockerfile

volumes:
  sqlsystem:
  redisdata:
  redistestdata:
