version: '3.4'

services:
  redis-test:
    container_name: redis-test
    ports:
      - "6370:6370"
    volumes:
      - redistestdata:/data

  redis:
    container_name: redis
    ports:
      - "6371:6371"
    volumes:
      - redisdata:/data

  ms-sql-server:
    container_name: sqlserverdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "12345678Ea#4"
    restart: always
    ports:
      - "1401:1433"
    volumes:
      - sqlsystem:/var/opt/mssql

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
    depends_on:
      - identity.api
    ports:
      - "7000:8000"

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__LocalDbContextConnection=Server=ms-sql-server;Database=identityDb;User Id=SA;Password=12345678Ea#4;TrustServerCertificate=True"
      - "JwtOptions__Issuer=WebLibrary"
      - "JwtOptions__Lifetime=120"
      - "JwtOptions__Audience=WebLibraryAudience"
      - "JwtOptions__Key=yB\bHgL1415r6TH%;jHpWz(Pdrvjy2Aq9xqMeartaer$524fsr_<8awzbsS^!kq':cbF5ygZ*yEE5pys#3z?@L6,zpfuP,?d"
    depends_on:
      - ms-sql-server
    ports:
      - "7001:8080"
      - "7071:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  categories.api:
    container_name: categories.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__LocalDbContextConnection=Server=ms-sql-server;Database=CategoriesDb;User Id=SA;Password=12345678Ea#4;TrustServerCertificate=True"
      - "ConnectionStrings__Redis=redis"
      - "JwtOptions__Issuer=WebLibrary"
      - "JwtOptions__Lifetime=120"
      - "JwtOptions__Audience=WebLibraryAudience"
      - "JwtOptions__Key=yB\bHgL1415r6TH%;jHpWz(Pdrvjy2Aq9xqMeartaer$524fsr_<8awzbsS^!kq':cbF5ygZ*yEE5pys#3z?@L6,zpfuP,?d"
    depends_on:
      - ms-sql-server
      - redis
    ports:
      - "7002:8080"
      - "7072:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  virtualpeople.api:
    container_name: virtual_people.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__LocalDbContextConnection=Server=ms-sql-server;Database=VirtualPeopleDb;User Id=SA;Password=12345678Ea#4;TrustServerCertificate=True"
      - "ConnectionStrings__Redis=redis"
      - "JwtOptions__Issuer=WebLibrary"
      - "JwtOptions__Lifetime=120"
      - "JwtOptions__Audience=WebLibraryAudience"
      - "JwtOptions__Key=yB\bHgL1415r6TH%;jHpWz(Pdrvjy2Aq9xqMeartaer$524fsr_<8awzbsS^!kq':cbF5ygZ*yEE5pys#3z?@L6,zpfuP,?d"
    depends_on:
      - ms-sql-server
      - redis
    ports:
      - "7003:8080"
      - "7073:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
