version: '3.4'

services:
  ms-sql-server:
    container_name: sqlserverdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "41924192Ge11$"
    restart: always
    ports:
      - "1401:1433"
    volumes:
      - sqlsystem:/var/opt/mssql

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
    depends_on:
      - identity.api
    ports:
      - "8000:8000"

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__LocalDbContextConnection=Server=ms-sql-server;Database=identityDb;User Id=SA;Password=41924192Ge11$;TrustServerCertificate=True"
      - "JwtOptions__Issuer=WebLibrary"
      - "JwtOptions__Lifetime=120"
      - "JwtOptions__Audience=WebLibraryAudience"
      - "JwtOptions__Key=yB\bHgL1415r6TH%;jHpWz(Pdrvjy2Aq9xqMeartaer$524fsr_<8awzbsS^!kq':cbF5ygZ*yEE5pys#3z?@L6,zpfuP,?d"
    depends_on:
      - ms-sql-server
    ports:
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro