version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.Api/Dockerfile

volumes:
  sqlsystem: